
baseURL = "https://upi05.github.io"
languageCode = "en"
DefaultContentLanguage = "en"
title = "Hieu Vo"

# theme as hugo module
#theme = "github.com/lxndrblz/anatole"
# theme as git submodule
theme = "anatole"

summarylength = 10
enableEmoji = true
enableRobotsTXT = true

# Enable Disqus
#disqusShortname = ""

# Google Analytics
#googleAnalytics = "UA-123-45"

# Syntax highlighting
pygmentsUseClasses = true   
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

# Localized dates requires Hugo version 0.87.0
localizedDates = false

[markup]
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe=true

[taxonomies]
    category = "categories"
    series = "series"
    tag = "tags"

[related]
  includeNewer = true
  threshold = 80
  toLower = true
[[related.indices]]
  name = 'keywords'
  weight = 100
[[related.indices]]
  name = 'tags'
  weight = 80

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

#  [[menu.main]]
#  name = "Posts"
#  weight = 200
#  identifier = "posts"
#  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:votruongtrunghieu@gmail.com"

[[params.socialIcons]]
icon = "fa-brands fa-github"
title = "github"
url = "https://github.com/upi05"

[[params.socialIcons]]
icon = "fa-solid fa-blog"
title = "viblo"
url = "https://viblo.asia/u/upi05"


[params]
title = "I'm Hieu Vo"
author = "Hieu Vo"
description = "Blockchain Reaseach Assistant at Vietnam Blockchain Innovation - VBI"
profilePicture = "images/logo2.png"
favicon = "favicons/favicon.ico"